image: node:10

cache:
  paths:
    - node_modules/

stages:
  - Checks


# ---------------------
# Checks stage jobs
# ---------------------

Tests:
  stage: Checks
  script:
    - npm install
    - npm run eslint --silent
    - npm test
